#use_frameworks!
install! 'cocoapods', :deterministic_uuids => false

source 'https://github.com/CocoaPods/Specs.git'



platform :ios, '9.0'

target 'AliyunVideoClient_Entrance' do
  
  #友盟crash收集
  pod 'UMCCommon','2.0.0'
  pod 'UMCAnalytics','6.0.1'
  
pod 'AlivcCommon', :path => 'AlivcCommon/' 
pod 'AlivcCore', :path => 'AlivcCore/' 
pod 'AlivcCrop', :path => 'AlivcCrop/' 
pod 'AlivcEdit', :path => 'AlivcEdit/' 
pod 'AlivcRecord', :path => 'AlivcRecord/' 
pod 'AlivcRace', :path => 'AlivcRace/' 



# pod 'AliyunRace', :git => 'https://github.com/aliyunvideo/AliyunRace.git',:tag => '1.1.1'

 
end
