use_frameworks!

ali_source 'alibaba-specs' #集团内部仓库

ali_source 'alibaba-specs-mirror' #官方镜像仓库

platform :ios, '9.0'

target 'AlivcEdit_Example' do
  pod 'AlivcEdit', :path => '../'
  
  pod 'AlivcCore', :path => '../../AlivcCore/'
  pod 'AlivcCommon', :path => '../../AlivcCommon/'
  target 'AlivcEdit_Tests' do
    inherit! :search_paths

    
  end
end
